### ISSUE TITLE
Single socket for both pubs and replies

### ISSUE THREAD

**Issue by jonahweissman** [melizalab/decide-rs#10]
Combining the socket for pubs and replies would allow us to guarantee that all "request is well formatted" confirmations would be sent before the corresponding state update pub message

**Comment by dmeliza** [comment]
This never got closed after our discussion. I believe we decided to keep them separate, so that we could distinguish programming errors (i.e. badly formatted requests) that should crash the client, from runtime errors, which the client could try to handle gracefully. @bpqle can you confirm?

**Comment by bpqle** [comment]
That is indeed the case currently - the controller can respond with b'ok' to requests that it can parse and direct the request towards the specific component's running thread. Runtime errors from the thread will mean no pub messages is sent out subsequently.
