### ISSUE TITLE
syslogd internal error 

### ISSUE THREAD

**Issue by bpqle** [melizalab/decide-rs#13]
Starting and killing decide-core multiple times in a row generates a chain of errors and requires a re-logon to access the beaglebone again:
![image](https://user-images.githubusercontent.com/83728412/154716268-21384724-2897-4bc3-8959-10bcaaeddfc8.png)

This negatively impacts beaglebone performance afterwards.

**Comment by bpqle** [comment]
#9

**Comment by dmeliza** [comment]
Closing this as having been addressed by fix to #9.
