### ISSUE TITLE
house lights component (sysfs)

### ISSUE THREAD

**Issue by dmeliza** [melizalab/decide-rs#4]

**Comment by bpqle** [comment]
Currently, the idiomatic Rust method to open the starboard light's brightness file is 

```rust
let mut file = std::fs::OpenOptions::new()
    .create(true)
    .write(true)
    .read(true)
    .open(FILE_PATH)
    .unwrap();
```
Even if the file is opened successfully in a single-thread program running on the beaglebone, attempting to write to the file results in `Os {code: 22}, kind: InvalidInput, message: Invalid argument`, while reading from the file is successful. The `File` returned by the above operation remains valid for retrieving `metadata()`, and can be identified as not read-only. Note that not having `write(true)` will result in the above operation failing with the same error. 

Using `std::fs::canonicalize("/sys/class/leds/starboard::lights/brightness")` to resolve any potential pathing issues does not solve the problem.
